/**
 * Every piece of UI copy lives here. Components never hardcode text.
 * Change wording (or add a language) in one place.
 */
export const STRINGS = {
  common: {
    toc: "Mục lục",
    readMinutes: (n: number) => `~${n} phút đọc`,
    demo: "Demo ↗",
    prev: "← Trước",
    next: "Tiếp →",
    viewAll: "Xem cả nhóm",
    tapToFlip: "chạm để xem nghĩa",
    docsCount: (n: number) => `${n} tài liệu`,
    howTo: "Cách làm →",
    send: "Gửi",
    loading: "Đang trả lời…",
  },
  nav: {
    home: "Trang chủ",
    today: "Hôm nay",
    docs: "Kiến thức",
    checklist: "Checklist",
    phrases: "Câu mẫu EN",
    assistant: "Trợ lý",
  },
  footer: {
    builtWith: "Next.js 16 · Tailwind v4 · Markdown → SSG · Vercel",
    github: "GitHub",
  },
  home: {
    headline: "Frontend & Mobile Developer.",
    subheadline: "React · Next.js · React Native.",
    intro: "5 năm TypeScript. Thích những bài toán client-side khó: realtime, offline, race condition, payment. Trang này vừa là portfolio, vừa là nơi tôi lưu kiến thức và bài học, đọc được trên điện thoại.",
    ctaDocs: "Đọc kiến thức",
    ctaGithub: "GitHub",
    work: "Dự án đã làm",
    knowledge: "Kho kiến thức",
    knowledgeDesc: "Markdown tự tổng hợp, song ngữ VI/EN, build tĩnh từ repo.",
    repos: "Dự án cá nhân trên GitHub",
  },
  today: {
    title: "Hôm nay làm gì",
    description: "Lịch theo thứ trong tuần, lấy từ E5 và E11. Mỗi khối có link mở ngay. Tích vào checklist khi xong.",
    weekend: "Cuối tuần: chỉ Mochi/Anki 10 phút khi dậy. Còn lại tuỳ hứng. CN tối ngủ trước 24h.",
    fullGuide: "Hướng dẫn đầy đủ (E11) →",
    plan: "Kế hoạch 6 tháng (E8) →",
    schedule: "Thời gian biểu (E5) →",
    checklist: "Checklist hôm nay →",
    open: "Mở",
    monthGoal: "Mốc tháng này",
    monthGoalHint: "Cuối tháng làm EF SET 50 phút (efset.org) và thu âm self-intro 2 phút. Ghi điểm vào ô bên dưới, lưu trên máy này.",
    efsetScore: "Điểm EF SET tháng này",
    efsetTarget: "Mục tiêu",
    unitsDone: "Unit Grammar in Use đã làm",
    reminders: "Giờ nhắc trong ngày",
    addToCalendar: "Thêm lịch nhắc vào iPhone (.ics) →",
    calendarHint: "Mở link trên iPhone → Thêm tất cả. Mỗi khối giờ sẽ có thông báo. Duolingo và Mochi đã nằm trong lịch.",
    apps: "App trên điện thoại",
    weekday: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
  },
  docs: {
    title: "Kho kiến thức",
    description: "Đọc theo thứ tự A → B/C → D. Ôn gấp thì đọc phần Q&A cuối mỗi file trước.",
    searchPlaceholder: "Tìm tài liệu… (ví dụ: redux, websocket, tiếng anh)",
    breadcrumb: "Kiến thức",
  },
  checklist: {
    title: "Checklist hôm nay",
    description: "Theo thời gian biểu E5. Ngày lười chỉ cần làm các dòng 🔴. Lưu trên máy này (localStorage), không cần đăng nhập.",
    minimum: "🔴 tối thiểu",
    streak: "Chuỗi ngày đạt",
    rule: "Luật: ngày lười làm dòng 🔴 vẫn tính đạt. Không bỏ 2 ngày liên tiếp.",
  },
  assistant: {
    title: "Trợ lý AI (Gemini)",
    description: "Hỏi đáp tự tìm trong toàn bộ kho tài liệu (hoặc chọn một file) và gia sư tiếng Anh A2. Mỗi cuộc hội thoại lưu trên máy này, xem lại ở tab Lịch sử.",
    modes: { ask: "Hỏi đáp", english: "Gia sư tiếng Anh" },
    tabs: { chat: "Trò chuyện", history: (n: number) => `Lịch sử (${n})` },
    newChat: "Cuộc mới",
    docPickerNone: "Tự tìm trong toàn bộ kho",
    docPickerLabel: "Hỏi về tài liệu",
    bubbleOpen: "Hỏi trợ lý",
    bubbleClose: "Đóng",
    bubbleFull: "Mở trang đầy đủ →",
    placeholder: { ask: "Ví dụ: giải thích useSyncExternalStore bằng tiếng Việt đơn giản", english: "Viết tiếng Anh, tôi sẽ sửa lỗi và hỏi tiếp" },
    history: {
      empty: "Chưa có cuộc hội thoại nào. Bắt đầu ở tab Trò chuyện.",
      count: (n: number) => `${n} tin`,
      deleteLabel: "Xoá cuộc này",
      deleteIcon: "🗑",
      clearAll: "Xoá tất cả",
      confirmClear: "Xoá toàn bộ lịch sử trợ lý trên máy này?",
      retention: (days: number, max: number) => `Tự xoá cuộc cũ hơn ${days} ngày, giữ tối đa ${max} cuộc.`,
    },
    errors: {
      no_key: "Server chưa có GEMINI_API_KEY. Thêm biến môi trường trên Vercel rồi deploy lại.",
      auth: "Yêu cầu không đến từ trang web này.",
      quota: "Hết hạn mức tạm thời. Đợi vài phút rồi thử lại.",
      busy: "Gemini đang quá tải. Thử lại sau vài giây.",
    },
    errorGeneric: "Có lỗi khi gọi Gemini. Thử lại.",
  },
  phrases: {
    title: "Câu mẫu tiếng Anh đi làm",
    description: "Câu ngắn, mức A2. Chạm thẻ để lật. Đọc to 5 lần mỗi câu.",
    sideEn: "🇬🇧 English",
    sideVi: "🇻🇳 Nghĩa",
    shuffle: "🔀",
  },
} as const;
